// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TVMazeScraper.Data;

#nullable disable

namespace TVMazeScraper.Migrations
{
    [DbContext(typeof(ProgramContext))]
    [Migration("20250525235559_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("TVMazeScraper.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("TVMazeScraper.Models.Show", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("TVMazeScraper.Models.ShowActor", b =>
                {
                    b.Property<int>("ShowID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActorID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ShowID", "ActorID");

                    b.HasIndex("ActorID");

                    b.ToTable("ShowActors");
                });

            modelBuilder.Entity("TVMazeScraper.Models.ShowActor", b =>
                {
                    b.HasOne("TVMazeScraper.Models.Actor", "Actor")
                        .WithMany("ShowActors")
                        .HasForeignKey("ActorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TVMazeScraper.Models.Show", "Show")
                        .WithMany("ShowActors")
                        .HasForeignKey("ShowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("TVMazeScraper.Models.Actor", b =>
                {
                    b.Navigation("ShowActors");
                });

            modelBuilder.Entity("TVMazeScraper.Models.Show", b =>
                {
                    b.Navigation("ShowActors");
                });
#pragma warning restore 612, 618
        }
    }
}
